&lt;%@ Page Language="C#" AutoEventWireup="true" CodeBehind="LandingPage.aspx.cs" Inherits="LoginSignup.LandingPage" %&gt;
&lt;!DOCTYPE html&gt;
&lt;html xmlns="http://www.w3.org/1999/xhtml"&gt;
&lt;head runat="server"&gt;
&lt;title&gt;&lt;/title&gt;
&lt;link href="Helper/css/style.default.css" rel="stylesheet" /&gt;
&lt;link href="Helper/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" /&gt;
&lt;/head&gt;
&lt;body&gt;
&lt;form id="form1" runat="server"&gt;
&lt;header class="header"&gt;
&lt;nav class="navbar navbar-expand-lg px-4 py-4 bg-white shadow"&gt;
&lt;/nav&gt;
&lt;/header&gt;
&lt;div class="page-holder w-100 d-flex flex-wrap"&gt;
&lt;div class="container-fluid px-x1-5"&gt;
&lt;section class="py-5"&gt;
&lt;div class="row"&gt;
&lt;div class="col-lg-4"&gt;
&lt;div class="card"&gt;
&lt;div class="card-header"&gt;
&lt;h3 class="h6 text-uppercase mb-0"&gt;Already have an account login here&lt;/h3&gt;
&lt;/div&gt;
&lt;div class="card-body"&gt;
&lt;a href="Login.aspx" type="button" class="btn btn-primary"&gt;Login&lt;/a&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;div class="col-lg-4"&gt;
&lt;div class="card"&gt;
&lt;div class="card-header"&gt;
&lt;h3 class="h6 text-uppercase mb-0"&gt;Don't have an account Sign up here&lt;/h3&gt;
&lt;/div&gt;
&lt;div class="card-body"&gt;
&lt;a href="Signup.aspx" type="button" class="btn btn-primary"&gt;Sign up&lt;/a&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/section&gt;
&lt;footer class="footer bg-white shadow align-self-end py-3 px-xl-5 w-100 " style="text-align:end;margin-top:390px"&gt;
&lt;div class="container-fluid"&gt;
&lt;div class="row"&gt;
&lt;div class="col-md-6 text-center text-md-left text-primary"&gt;
&lt;p class ="mb-2 mb-md-0"&gt;RashiCode &amp;copy;2021&lt;/p&gt;
&lt;/div&gt;
&lt;div class="col-md-6 text-center text-md-right text-gray-400"&gt;
&lt;p class="mb-0"&gt;DEsign by &lt;a href="#"&gt;Rashicode&lt;/a&gt;&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/footer&gt;
&lt;/div&gt;
&lt;/div&gt;
&lt;/form&gt;
&lt;/body&gt;
&lt;/html&gt;